#!/usr/bin/env python3
"""Published-plugin immutability ledger.

Once a plugin version is published into the registry, its manifest and every
declared payload file are frozen. Compatibility mistakes are corrected with a
registry-level ``compatibility_override`` (see ``schema_compatibility.py``),
never by editing package bytes: rewriting a published payload changes what
already-installed clients verified against.

``published-plugin-lock.json`` is the single source of truth. It is
deliberately *not* regenerated by ``refresh_hashes.py`` or by any validation
step, so the usual "edit payload, refresh manifest hash, refresh registry
hash" sequence can never bless a mutation - the ledger still holds the
original digests and validation fails closed.

Recording a newly published version is an explicit, additive action:

    python scripts/published_lock.py --record org.hpcclient.truba@1.6.0

An already recorded version is never overwritten by that command. A genuine
one-time exception (a mutation that predates this policy) must be written by
hand with a ``frozen_reason`` explaining it, so the violation stays visible in
the ledger and in review.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCK_NAME = "published-plugin-lock.json"

IMMUTABLE_MESSAGE = (
    "Published plugin {plugin_id}@{version} is immutable. "
    "Create a new plugin version instead of modifying its payload."
)


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def lock_key(plugin_id: str, version: str) -> str:
    return f"{plugin_id}@{version}"


def load_lock(root: Path | None = None) -> dict:
    path = (root or REPO_ROOT) / LOCK_NAME
    if not path.is_file():
        return {"schema_version": 1, "published": {}}
    return json.loads(path.read_text(encoding="utf-8"))


def record_for(manifest_path: Path) -> dict:
    """Digest record for a package as it currently exists on disk."""
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    files = {}
    for declared in manifest.get("files", []):
        payload = manifest_path.parent / declared["path"]
        files[declared["path"]] = sha256_of(payload)
    return {
        "manifest_sha256": sha256_of(manifest_path),
        "files": dict(sorted(files.items())),
    }


def immutability_errors(root: Path, registry: dict) -> list[str]:
    """Errors for any published package whose bytes no longer match the ledger.

    Only registry entries that appear in the ledger are checked: a version
    that has never been published is still free to change.
    """
    lock = load_lock(root)
    published = lock.get("published", {})
    errors: list[str] = []

    for entry in registry.get("plugins", []):
        key = lock_key(entry["id"], entry["version"])
        recorded = published.get(key)
        if recorded is None:
            continue
        manifest_path = root / entry["manifest_path"]
        if not manifest_path.is_file():
            errors.append(
                f"{key}: published manifest is missing; "
                + IMMUTABLE_MESSAGE.format(
                    plugin_id=entry["id"], version=entry["version"]
                )
            )
            continue
        prefix = IMMUTABLE_MESSAGE.format(
            plugin_id=entry["id"], version=entry["version"]
        )
        actual_manifest = sha256_of(manifest_path)
        if actual_manifest != recorded["manifest_sha256"]:
            errors.append(
                f"{prefix} manifest.json sha256 "
                f"{actual_manifest} != published {recorded['manifest_sha256']}"
            )
        actual_files = record_for(manifest_path)["files"]
        recorded_files = recorded.get("files", {})
        for path, digest in sorted(recorded_files.items()):
            current = actual_files.get(path)
            if current is None:
                errors.append(f"{prefix} declared payload '{path}' was removed")
            elif current != digest:
                errors.append(
                    f"{prefix} payload '{path}' sha256 {current} != published {digest}"
                )
        for path in sorted(set(actual_files) - set(recorded_files)):
            errors.append(f"{prefix} payload '{path}' was added after publication")

    return errors


def _registry(root: Path) -> dict:
    return json.loads((root / "registry.json").read_text(encoding="utf-8"))


def record(target: str, root: Path = REPO_ROOT) -> int:
    try:
        plugin_id, version = target.split("@", 1)
    except ValueError:
        print("Expected <plugin-id>@<version>", file=sys.stderr)
        return 2
    registry = _registry(root)
    entry = next(
        (
            item
            for item in registry["plugins"]
            if item["id"] == plugin_id and item["version"] == version
        ),
        None,
    )
    if entry is None:
        print(f"{target} is not in registry.json", file=sys.stderr)
        return 1

    lock_path = root / LOCK_NAME
    lock = load_lock(root)
    published = lock.setdefault("published", {})
    key = lock_key(plugin_id, version)
    if key in published:
        print(
            f"{key} is already published and frozen; "
            "create a new plugin version instead.",
            file=sys.stderr,
        )
        return 1
    published[key] = record_for(root / entry["manifest_path"])
    lock["published"] = dict(sorted(published.items()))
    lock_path.write_text(
        json.dumps(lock, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Recorded {key}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--record",
        metavar="ID@VERSION",
        help="freeze a newly published plugin version (never overwrites)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify every frozen package still matches the ledger",
    )
    args = parser.parse_args()
    if args.record:
        return record(args.record)
    errors = immutability_errors(REPO_ROOT, _registry(REPO_ROOT))
    if errors:
        print(f"FAIL: {len(errors)} immutability problem(s):")
        for error in errors:
            print(f"  - {error}")
        return 1
    print("OK: every published plugin package matches the ledger.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
