#!/usr/bin/env python3
"""Published-plugin immutability ledger and publication completeness.

Once a plugin version is published into the registry, its manifest and every
declared payload file are frozen. Compatibility mistakes are corrected with a
registry-level ``compatibility_override`` (see ``schema_compatibility.py``),
never by editing package bytes: rewriting a published payload changes what
already-installed clients verified against.

A ledger of digests alone is not enough. It protects what it lists, so the
obvious escape is to stop listing something. ``published-plugin-lock.json``
therefore carries two separate things:

``publication_index``
    The roster of every plugin version that has ever been published. It is
    append-only. Nothing is ever removed from it, because publication is a
    historical fact and deleting the record does not un-publish the bytes
    someone already downloaded.

``published``
    The frozen digests for each of those versions.

Validation enforces completeness in both directions:

1. Every version published on ``main`` is in the index. The authoritative
   published set is ``main``'s own ``registry.json``, read through git - a
   fact that cannot be edited from a topic branch. When git or ``main`` is
   unreachable (a shallow CI checkout, an exported tree), the index itself
   is the floor, and the check degrades to "the index is authoritative"
   rather than to "anything goes".
2. Every indexed version still has a digest record, a registry row, a
   manifest, and every declared payload file, and all of them still match.

So deleting a lock record, deleting a registry row, or deleting the package
directory all fail closed, and the "edit payload, refresh every hash" cycle
still cannot bless a mutation: the digests in the ledger are never
regenerated by ``refresh_hashes.py`` or by any validation step.

Recording a newly published version is an explicit, additive action:

    python scripts/published_lock.py --record org.hpcclient.truba@1.6.0

An already recorded version is never overwritten by that command. A genuine
one-time exception (a mutation that predates this policy) must be written by
hand with a ``frozen_reason`` explaining it, so the violation stays visible in
the ledger and in review.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCK_NAME = "published-plugin-lock.json"

# The branch whose registry.json defines what is actually published.
PUBLICATION_BRANCH_CANDIDATES = ("origin/main", "main")

IMMUTABLE_MESSAGE = (
    "Published plugin {plugin_id}@{version} is immutable. "
    "Create a new plugin version instead of modifying its payload."
)
UNFREEZE_MESSAGE = (
    "Published plugin {key} is missing from {what}. Publication is permanent: "
    "record it with scripts/published_lock.py --record, and never remove a "
    "published version from the registry, the package tree, or the ledger."
)


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def lock_key(plugin_id: str, version: str) -> str:
    return f"{plugin_id}@{version}"


def load_lock(root: Path | None = None) -> dict:
    path = (root or REPO_ROOT) / LOCK_NAME
    if not path.is_file():
        return {"schema_version": 2, "publication_index": [], "published": {}}
    return json.loads(path.read_text(encoding="utf-8"))


def publication_index(lock: dict) -> set[str]:
    """Every version the ledger says has ever been published."""
    index = lock.get("publication_index")
    if isinstance(index, list):
        return {str(item) for item in index}
    # A schema-1 ledger had no separate roster; its digest records were the
    # roster. Treat them as such so an old ledger is never silently emptied.
    return set(lock.get("published", {}))


def record_for(manifest_path: Path) -> dict:
    """Digest record for a package as it currently exists on disk."""
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    files = {}
    for declared in manifest.get("files", []):
        payload = manifest_path.parent / declared["path"]
        files[declared["path"]] = sha256_of(payload)
    return {
        "manifest_sha256": sha256_of(manifest_path),
        "files": dict(sorted(files.items())),
    }


def _git_show(root: Path, ref: str, path: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", "show", f"{ref}:{path}"],
            cwd=str(root),
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=30,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    return result.stdout


def main_published_keys(root: Path) -> set[str] | None:
    """Versions published on ``main``, or ``None`` when git cannot say.

    This is the authoritative definition of "published": a version is
    published once ``main``'s registry advertises it. A topic branch cannot
    rewrite that, which is what makes the completeness check meaningful.
    """
    for ref in PUBLICATION_BRANCH_CANDIDATES:
        payload = _git_show(root, ref, "registry.json")
        if payload is None:
            continue
        try:
            registry = json.loads(payload)
        except json.JSONDecodeError:
            return None
        return {
            lock_key(str(entry.get("id")), str(entry.get("version")))
            for entry in registry.get("plugins", [])
            if isinstance(entry, dict)
        }
    return None


def _registry_keys(registry: dict) -> dict[str, dict]:
    return {
        lock_key(str(entry.get("id")), str(entry.get("version"))): entry
        for entry in registry.get("plugins", [])
        if isinstance(entry, dict)
    }


def completeness_errors(root: Path, registry: dict, lock: dict) -> list[str]:
    """Publication history may never shrink.

    Direction 1: everything published on ``main`` is in the index.
    Direction 2: everything in the index still has a digest record, a
    registry row, and a package on disk.
    """
    errors: list[str] = []
    index = publication_index(lock)
    published = lock.get("published", {})
    present = _registry_keys(registry)

    authoritative = main_published_keys(root)
    if authoritative is not None:
        for key in sorted(authoritative - index):
            errors.append(
                f"{key} is published on main but missing from the ledger's "
                "publication_index; freeze it with "
                "scripts/published_lock.py --record"
            )

    for key in sorted(index):
        if key not in published:
            errors.append(UNFREEZE_MESSAGE.format(key=key, what="the ledger digests"))
            continue
        entry = present.get(key)
        if entry is None:
            errors.append(UNFREEZE_MESSAGE.format(key=key, what="registry.json"))
            continue
        manifest_path = root / str(entry.get("manifest_path", ""))
        if not manifest_path.is_file():
            errors.append(UNFREEZE_MESSAGE.format(key=key, what="the package tree"))
    return errors


def immutability_errors(root: Path, registry: dict) -> list[str]:
    """Frozen bytes must still match, and publication history must not shrink.

    Every indexed version is checked from the ledger outwards, not from the
    current registry inwards, so removing a row or a directory cannot make
    its protection quietly irrelevant.
    """
    lock = load_lock(root)
    published = lock.get("published", {})
    present = _registry_keys(registry)
    errors: list[str] = completeness_errors(root, registry, lock)

    for key in sorted(publication_index(lock) | set(published)):
        recorded = published.get(key)
        if recorded is None:
            continue  # already reported by completeness
        entry = present.get(key)
        if entry is None:
            continue  # already reported by completeness
        plugin_id, _, version = key.partition("@")
        prefix = IMMUTABLE_MESSAGE.format(plugin_id=plugin_id, version=version)
        manifest_path = root / str(entry.get("manifest_path", ""))
        if not manifest_path.is_file():
            continue  # already reported by completeness

        actual_manifest = sha256_of(manifest_path)
        if actual_manifest != recorded["manifest_sha256"]:
            errors.append(
                f"{prefix} manifest.json sha256 "
                f"{actual_manifest} != published {recorded['manifest_sha256']}"
            )

        recorded_files = recorded.get("files", {})
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        declared = {item["path"] for item in manifest.get("files", [])}
        actual_files: dict[str, str] = {}
        for path in sorted(declared):
            payload = manifest_path.parent / path
            if payload.is_file():
                actual_files[path] = sha256_of(payload)

        for path, digest in sorted(recorded_files.items()):
            current = actual_files.get(path)
            if current is None:
                errors.append(f"{prefix} declared payload '{path}' was removed")
            elif current != digest:
                errors.append(
                    f"{prefix} payload '{path}' sha256 {current} != published {digest}"
                )
        for path in sorted(set(actual_files) - set(recorded_files)):
            errors.append(f"{prefix} payload '{path}' was added after publication")

    return errors


def _registry(root: Path) -> dict:
    return json.loads((root / "registry.json").read_text(encoding="utf-8"))


def record(target: str, root: Path = REPO_ROOT) -> int:
    try:
        plugin_id, version = target.split("@", 1)
    except ValueError:
        print("Expected <plugin-id>@<version>", file=sys.stderr)
        return 2
    registry = _registry(root)
    entry = _registry_keys(registry).get(lock_key(plugin_id, version))
    if entry is None:
        print(f"{target} is not in registry.json", file=sys.stderr)
        return 1

    manifest_path = root / str(entry.get("manifest_path", ""))
    if not manifest_path.is_file():
        print(f"{target}: manifest not found at {entry.get('manifest_path')}", file=sys.stderr)
        return 1
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    for declared in manifest.get("files", []):
        payload = manifest_path.parent / declared["path"]
        if not payload.is_file():
            print(f"{target}: declared payload missing: {declared['path']}", file=sys.stderr)
            return 1
        actual = sha256_of(payload)
        if actual != declared.get("sha256"):
            print(
                f"{target}: payload '{declared['path']}' does not match its "
                f"declared sha256; fix the package before freezing it.",
                file=sys.stderr,
            )
            return 1
    if sha256_of(manifest_path) != entry.get("manifest_sha256"):
        print(
            f"{target}: manifest does not match registry manifest_sha256; "
            "fix the registry before freezing it.",
            file=sys.stderr,
        )
        return 1

    lock_path = root / LOCK_NAME
    lock = load_lock(root)
    published = lock.setdefault("published", {})
    key = lock_key(plugin_id, version)
    if key in published:
        print(
            f"{key} is already published and frozen; "
            "create a new plugin version instead.",
            file=sys.stderr,
        )
        return 1
    published[key] = record_for(manifest_path)
    lock["published"] = dict(sorted(published.items()))
    lock["publication_index"] = sorted(publication_index(lock) | {key})
    lock.setdefault("schema_version", 2)
    lock_path.write_text(
        json.dumps(lock, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Recorded {key}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--record",
        metavar="ID@VERSION",
        help="freeze a newly published plugin version (never overwrites)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the ledger is complete and every frozen package matches",
    )
    args = parser.parse_args()
    if args.record:
        return record(args.record)
    errors = immutability_errors(REPO_ROOT, _registry(REPO_ROOT))
    if errors:
        print(f"FAIL: {len(errors)} immutability problem(s):")
        for error in errors:
            print(f"  - {error}")
        return 1
    print("OK: the publication ledger is complete and every package matches.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
